### ISSUE TITLE
Possibilities of generating TM score

### ISSUE THREAD

**Issue by Jiachen2000** [seanrjohnson/esmologs#3]
Hello,

Sorry to bother you! I am reaching out because I have been trying to use ESMologs to run structural homolog searches and compare the search results with those directly from Foldseek.
In the "Run Foldseek searches" section, I wonder if it is possible to also calculate the TM score and include that as output. I've tried but always failed as no C-alpha information is given from the generating 3Di sequence step. If obtaining C-alpha information is impossible from ESMologs, may I ask if there is any way to compare the 3Di sequences predicted by ESMologs with the 3Di sequences generated by Foldseek?

Many thanks for considering my request.

BR
Jiachen

**Comment by seanrjohnson** [comment]
Hi Jiachen,

Thanks for using this code. This repository won't give you C-alpha coordinates. To get those, you'd have to use ESMFold, or some other full structure prediction model. There are many models that do that. As far as I know, they are all slower the amino acid to 3Di approach we take in this repo.

You can definitely compare 3Di sequences between Foldseek generated databases and 3Di sequences generated from ESMologs.

Here's an example (I didn't test this, so maybe there are some typos, but you'll get the idea)

```
#Download swissprot foldseek database
foldseek databases Alphafold/Swiss-Prot swissprot  tmp

#extract peptide and 3di fastas
foldseek2fasta.py -i swissprot -o swissprot

#filter proteins less than 120 aa or greater than 1000 aa
filter_fasta.py -i swissprot.pep.fasta -o swissprot.pep.120_1000aa.fasta
filter_fasta.py -i swissprot.3di.fasta -o swissprot.3di.120_1000aa.fasta

# convert aa fasta to 3di using ESMologs
# might take a while, might want to test this first on a smaller database, like PDB, or something even smaller

predict_from_ESM2_to_3Di.py --weights ESM-2_3B_3Di.pt -i swissprot.pep.120_1000aa.fasta -o swissprot.esm.120_1000aa.fasta

#compare ESMologs predictions to original database using 
# https://github.com/seanrjohnson/esmologs/blob/main/src/esmologs/calculate_accuracy.py
python calculate_accuracy.py -i swissprot.esm.120_1000aa.fasta -r swissprot.3di.120_1000aa.fasta -m mismatch_matrix.txt

```

**Comment by Jiachen2000** [comment]
Thank you so much!
